// This file was auto-generated by Fern from our API Definition.

package client

import (
	cluster "github.com/hookdeck/hookdeck-go-sdk/cluster"
	collections "github.com/hookdeck/hookdeck-go-sdk/collections"
	core "github.com/hookdeck/hookdeck-go-sdk/core"
	points "github.com/hookdeck/hookdeck-go-sdk/points"
	service "github.com/hookdeck/hookdeck-go-sdk/service"
	snapshots "github.com/hookdeck/hookdeck-go-sdk/snapshots"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *core.Caller
	header  http.Header

	Collections *collections.Client
	Service     *service.Client
	Cluster     *cluster.Client
	Snapshots   *snapshots.Client
	Points      *points.Client
}

func NewClient(opts ...core.ClientOption) *Client {
	options := core.NewClientOptions()
	for _, opt := range opts {
		opt(options)
	}
	return &Client{
		baseURL:     options.BaseURL,
		caller:      core.NewCaller(options.HTTPClient),
		header:      options.ToHeader(),
		Collections: collections.NewClient(opts...),
		Service:     service.NewClient(opts...),
		Cluster:     cluster.NewClient(opts...),
		Snapshots:   snapshots.NewClient(opts...),
		Points:      points.NewClient(opts...),
	}
}
