// This file was auto-generated by Fern from our API Definition.

package client

import (
	attempts "github.com/hookdeck/hookdeck-go-sdk/attempts"
	bookmarks "github.com/hookdeck/hookdeck-go-sdk/bookmarks"
	bulkretryevents "github.com/hookdeck/hookdeck-go-sdk/bulkretryevents"
	bulkretryignoredevents "github.com/hookdeck/hookdeck-go-sdk/bulkretryignoredevents"
	bulkretryrequests "github.com/hookdeck/hookdeck-go-sdk/bulkretryrequests"
	connections "github.com/hookdeck/hookdeck-go-sdk/connections"
	core "github.com/hookdeck/hookdeck-go-sdk/core"
	destinations "github.com/hookdeck/hookdeck-go-sdk/destinations"
	events "github.com/hookdeck/hookdeck-go-sdk/events"
	integrations "github.com/hookdeck/hookdeck-go-sdk/integrations"
	issues "github.com/hookdeck/hookdeck-go-sdk/issues"
	issuetriggers "github.com/hookdeck/hookdeck-go-sdk/issuetriggers"
	notifications "github.com/hookdeck/hookdeck-go-sdk/notifications"
	requests "github.com/hookdeck/hookdeck-go-sdk/requests"
	sources "github.com/hookdeck/hookdeck-go-sdk/sources"
	transformations "github.com/hookdeck/hookdeck-go-sdk/transformations"
	http "net/http"
)

type Client interface {
	IssueTriggers() issuetriggers.Client
	Attempts() attempts.Client
	Bookmarks() bookmarks.Client
	Destinations() destinations.Client
	BulkRetryEvents() bulkretryevents.Client
	Events() events.Client
	BulkRetryIgnoredEvents() bulkretryignoredevents.Client
	Integrations() integrations.Client
	Issues() issues.Client
	Requests() requests.Client
	BulkRetryRequests() bulkretryrequests.Client
	Sources() sources.Client
	Notifications() notifications.Client
	Transformations() transformations.Client
	Connections() connections.Client
}

func NewClient(opts ...core.ClientOption) Client {
	options := core.NewClientOptions()
	for _, opt := range opts {
		opt(options)
	}
	return &client{
		baseURL:                      options.BaseURL,
		httpClient:                   options.HTTPClient,
		header:                       options.ToHeader(),
		issueTriggersClient:          issuetriggers.NewClient(opts...),
		attemptsClient:               attempts.NewClient(opts...),
		bookmarksClient:              bookmarks.NewClient(opts...),
		destinationsClient:           destinations.NewClient(opts...),
		bulkRetryEventsClient:        bulkretryevents.NewClient(opts...),
		eventsClient:                 events.NewClient(opts...),
		bulkRetryIgnoredEventsClient: bulkretryignoredevents.NewClient(opts...),
		integrationsClient:           integrations.NewClient(opts...),
		issuesClient:                 issues.NewClient(opts...),
		requestsClient:               requests.NewClient(opts...),
		bulkRetryRequestsClient:      bulkretryrequests.NewClient(opts...),
		sourcesClient:                sources.NewClient(opts...),
		notificationsClient:          notifications.NewClient(opts...),
		transformationsClient:        transformations.NewClient(opts...),
		connectionsClient:            connections.NewClient(opts...),
	}
}

type client struct {
	baseURL                      string
	httpClient                   core.HTTPClient
	header                       http.Header
	issueTriggersClient          issuetriggers.Client
	attemptsClient               attempts.Client
	bookmarksClient              bookmarks.Client
	destinationsClient           destinations.Client
	bulkRetryEventsClient        bulkretryevents.Client
	eventsClient                 events.Client
	bulkRetryIgnoredEventsClient bulkretryignoredevents.Client
	integrationsClient           integrations.Client
	issuesClient                 issues.Client
	requestsClient               requests.Client
	bulkRetryRequestsClient      bulkretryrequests.Client
	sourcesClient                sources.Client
	notificationsClient          notifications.Client
	transformationsClient        transformations.Client
	connectionsClient            connections.Client
}

func (c *client) IssueTriggers() issuetriggers.Client {
	return c.issueTriggersClient
}

func (c *client) Attempts() attempts.Client {
	return c.attemptsClient
}

func (c *client) Bookmarks() bookmarks.Client {
	return c.bookmarksClient
}

func (c *client) Destinations() destinations.Client {
	return c.destinationsClient
}

func (c *client) BulkRetryEvents() bulkretryevents.Client {
	return c.bulkRetryEventsClient
}

func (c *client) Events() events.Client {
	return c.eventsClient
}

func (c *client) BulkRetryIgnoredEvents() bulkretryignoredevents.Client {
	return c.bulkRetryIgnoredEventsClient
}

func (c *client) Integrations() integrations.Client {
	return c.integrationsClient
}

func (c *client) Issues() issues.Client {
	return c.issuesClient
}

func (c *client) Requests() requests.Client {
	return c.requestsClient
}

func (c *client) BulkRetryRequests() bulkretryrequests.Client {
	return c.bulkRetryRequestsClient
}

func (c *client) Sources() sources.Client {
	return c.sourcesClient
}

func (c *client) Notifications() notifications.Client {
	return c.notificationsClient
}

func (c *client) Transformations() transformations.Client {
	return c.transformationsClient
}

func (c *client) Connections() connections.Client {
	return c.connectionsClient
}
