// This file was auto-generated by Fern from our API Definition.

package api

type ApiKeyIntegrationConfigs struct {
	HeaderKey string `json:"header_key,omitempty"`
	ApiKey    string `json:"api_key,omitempty"`
}
