// This file was auto-generated by Fern from our API Definition.

package api

import (
	fmt "fmt"
)

type AttemptListRequest struct {
	EventId []*string                  `json:"-" url:"event_id,omitempty"`
	OrderBy *AttemptListRequestOrderBy `json:"-" url:"order_by,omitempty"`
	Dir     *AttemptListRequestDir     `json:"-" url:"dir,omitempty"`
	Limit   *int                       `json:"-" url:"limit,omitempty"`
	Next    *string                    `json:"-" url:"next,omitempty"`
	Prev    *string                    `json:"-" url:"prev,omitempty"`
}

type AttemptListRequestDir string

const (
	AttemptListRequestDirAsc  AttemptListRequestDir = "asc"
	AttemptListRequestDirDesc AttemptListRequestDir = "desc"
)

func NewAttemptListRequestDirFromString(s string) (AttemptListRequestDir, error) {
	switch s {
	case "asc":
		return AttemptListRequestDirAsc, nil
	case "desc":
		return AttemptListRequestDirDesc, nil
	}
	var t AttemptListRequestDir
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AttemptListRequestDir) Ptr() *AttemptListRequestDir {
	return &a
}

type AttemptListRequestOrderBy string

const (
	AttemptListRequestOrderByCreatedAt AttemptListRequestOrderBy = "created_at"
)

func NewAttemptListRequestOrderByFromString(s string) (AttemptListRequestOrderBy, error) {
	switch s {
	case "created_at":
		return AttemptListRequestOrderByCreatedAt, nil
	}
	var t AttemptListRequestOrderBy
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AttemptListRequestOrderBy) Ptr() *AttemptListRequestOrderBy {
	return &a
}
