// This file was auto-generated by Fern from our API Definition.

package api

type BasicAuthIntegrationConfigs struct {
	Name     string `json:"name,omitempty"`
	Password string `json:"password,omitempty"`
}
