// This file was auto-generated by Fern from our API Definition.

package api

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	errors "errors"
	fmt "fmt"
	core "github.com/fern-hookdeck/hookdeck-go/core"
	io "io"
	http "net/http"
	url "net/url"
)

type BulkRetryRequestsClient interface {
	GetRequestBulkRetries(ctx context.Context, request *GetRequestBulkRetriesRequest) (*BatchOperationPaginatedResult, error)
	CreateRequestBulkRetry(ctx context.Context, request *CreateRequestBulkRetryRequest) (*BatchOperation, error)
	GenerateRequestBulkRetryPlan(ctx context.Context) (*BatchOperationPlan, error)
	GetRequestBulkRetry(ctx context.Context, id string) (*BatchOperation, error)
	CancelRequestBulkRetry(ctx context.Context, id string) (*BatchOperation, error)
}

func NewBulkRetryRequestsClient(opts ...core.ClientOption) BulkRetryRequestsClient {
	options := core.NewClientOptions()
	for _, opt := range opts {
		opt(options)
	}
	return &bulkRetryRequestsClient{
		baseURL:    options.BaseURL,
		httpClient: options.HTTPClient,
		header:     options.ToHeader(),
	}
}

type bulkRetryRequestsClient struct {
	baseURL    string
	httpClient core.HTTPClient
	header     http.Header
}

func (b *bulkRetryRequestsClient) GetRequestBulkRetries(ctx context.Context, request *GetRequestBulkRetriesRequest) (*BatchOperationPaginatedResult, error) {
	baseURL := "https://api.hookdeck.com/2023-01-01"
	if b.baseURL != "" {
		baseURL = b.baseURL
	}
	endpointURL := baseURL + "/" + "bulk/requests/retry"

	queryParams := make(url.Values)
	var cancelledAtDefaultValue *string
	if request.CancelledAt != cancelledAtDefaultValue {
		queryParams.Add("cancelled_at", fmt.Sprintf("%v", *request.CancelledAt))
	}
	var completedAtDefaultValue *string
	if request.CompletedAt != completedAtDefaultValue {
		queryParams.Add("completed_at", fmt.Sprintf("%v", *request.CompletedAt))
	}
	var createdAtDefaultValue *string
	if request.CreatedAt != createdAtDefaultValue {
		queryParams.Add("created_at", fmt.Sprintf("%v", *request.CreatedAt))
	}
	var idDefaultValue *string
	if request.Id != idDefaultValue {
		queryParams.Add("id", fmt.Sprintf("%v", *request.Id))
	}
	var inProgressDefaultValue *bool
	if request.InProgress != inProgressDefaultValue {
		queryParams.Add("in_progress", fmt.Sprintf("%v", *request.InProgress))
	}
	var queryPartialMatchDefaultValue *bool
	if request.QueryPartialMatch != queryPartialMatchDefaultValue {
		queryParams.Add("query_partial_match", fmt.Sprintf("%v", *request.QueryPartialMatch))
	}
	var orderByDefaultValue *string
	if request.OrderBy != orderByDefaultValue {
		queryParams.Add("order_by", fmt.Sprintf("%v", *request.OrderBy))
	}
	var dirDefaultValue *GetRequestBulkRetriesRequestDirGetRequestBulkRetriesRequestDir
	if request.Dir != dirDefaultValue {
		queryParams.Add("dir", fmt.Sprintf("%v", *request.Dir))
	}
	var limitDefaultValue *int
	if request.Limit != limitDefaultValue {
		queryParams.Add("limit", fmt.Sprintf("%v", *request.Limit))
	}
	var nextDefaultValue *string
	if request.Next != nextDefaultValue {
		queryParams.Add("next", fmt.Sprintf("%v", *request.Next))
	}
	var prevDefaultValue *string
	if request.Prev != prevDefaultValue {
		queryParams.Add("prev", fmt.Sprintf("%v", *request.Prev))
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}

	errorDecoder := func(statusCode int, body io.Reader) error {
		raw, err := io.ReadAll(body)
		if err != nil {
			return err
		}
		apiError := core.NewAPIError(statusCode, errors.New(string(raw)))
		decoder := json.NewDecoder(bytes.NewReader(raw))
		switch statusCode {
		case 400:
			value := new(BadRequestError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return err
			}
			return value
		case 422:
			value := new(UnprocessableEntityError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return err
			}
			return value
		}
		return apiError
	}

	response := new(BatchOperationPaginatedResult)
	if err := core.DoRequest(
		ctx,
		b.httpClient,
		endpointURL,
		http.MethodGet,
		request,
		&response,
		b.header,
		errorDecoder,
	); err != nil {
		return response, err
	}
	return response, nil
}

func (b *bulkRetryRequestsClient) CreateRequestBulkRetry(ctx context.Context, request *CreateRequestBulkRetryRequest) (*BatchOperation, error) {
	baseURL := "https://api.hookdeck.com/2023-01-01"
	if b.baseURL != "" {
		baseURL = b.baseURL
	}
	endpointURL := baseURL + "/" + "bulk/requests/retry"

	errorDecoder := func(statusCode int, body io.Reader) error {
		raw, err := io.ReadAll(body)
		if err != nil {
			return err
		}
		apiError := core.NewAPIError(statusCode, errors.New(string(raw)))
		decoder := json.NewDecoder(bytes.NewReader(raw))
		switch statusCode {
		case 400:
			value := new(BadRequestError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return err
			}
			return value
		case 422:
			value := new(UnprocessableEntityError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return err
			}
			return value
		}
		return apiError
	}

	response := new(BatchOperation)
	if err := core.DoRequest(
		ctx,
		b.httpClient,
		endpointURL,
		http.MethodPost,
		request,
		&response,
		b.header,
		errorDecoder,
	); err != nil {
		return response, err
	}
	return response, nil
}

func (b *bulkRetryRequestsClient) GenerateRequestBulkRetryPlan(ctx context.Context) (*BatchOperationPlan, error) {
	baseURL := "https://api.hookdeck.com/2023-01-01"
	if b.baseURL != "" {
		baseURL = b.baseURL
	}
	endpointURL := baseURL + "/" + "bulk/requests/retry/plan"

	errorDecoder := func(statusCode int, body io.Reader) error {
		raw, err := io.ReadAll(body)
		if err != nil {
			return err
		}
		apiError := core.NewAPIError(statusCode, errors.New(string(raw)))
		decoder := json.NewDecoder(bytes.NewReader(raw))
		switch statusCode {
		case 400:
			value := new(BadRequestError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return err
			}
			return value
		case 422:
			value := new(UnprocessableEntityError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return err
			}
			return value
		}
		return apiError
	}

	response := new(BatchOperationPlan)
	if err := core.DoRequest(
		ctx,
		b.httpClient,
		endpointURL,
		http.MethodGet,
		nil,
		&response,
		b.header,
		errorDecoder,
	); err != nil {
		return response, err
	}
	return response, nil
}

func (b *bulkRetryRequestsClient) GetRequestBulkRetry(ctx context.Context, id string) (*BatchOperation, error) {
	baseURL := "https://api.hookdeck.com/2023-01-01"
	if b.baseURL != "" {
		baseURL = b.baseURL
	}
	endpointURL := fmt.Sprintf(baseURL+"/"+"bulk/requests/retry/%v", id)

	errorDecoder := func(statusCode int, body io.Reader) error {
		raw, err := io.ReadAll(body)
		if err != nil {
			return err
		}
		apiError := core.NewAPIError(statusCode, errors.New(string(raw)))
		decoder := json.NewDecoder(bytes.NewReader(raw))
		switch statusCode {
		case 404:
			value := new(NotFoundError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return err
			}
			return value
		}
		return apiError
	}

	response := new(BatchOperation)
	if err := core.DoRequest(
		ctx,
		b.httpClient,
		endpointURL,
		http.MethodGet,
		nil,
		&response,
		b.header,
		errorDecoder,
	); err != nil {
		return response, err
	}
	return response, nil
}

func (b *bulkRetryRequestsClient) CancelRequestBulkRetry(ctx context.Context, id string) (*BatchOperation, error) {
	baseURL := "https://api.hookdeck.com/2023-01-01"
	if b.baseURL != "" {
		baseURL = b.baseURL
	}
	endpointURL := fmt.Sprintf(baseURL+"/"+"bulk/requests/retry/%v/cancel", id)

	errorDecoder := func(statusCode int, body io.Reader) error {
		raw, err := io.ReadAll(body)
		if err != nil {
			return err
		}
		apiError := core.NewAPIError(statusCode, errors.New(string(raw)))
		decoder := json.NewDecoder(bytes.NewReader(raw))
		switch statusCode {
		case 404:
			value := new(NotFoundError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return err
			}
			return value
		}
		return apiError
	}

	response := new(BatchOperation)
	if err := core.DoRequest(
		ctx,
		b.httpClient,
		endpointURL,
		http.MethodPost,
		nil,
		&response,
		b.header,
		errorDecoder,
	); err != nil {
		return response, err
	}
	return response, nil
}
