// This file was auto-generated by Fern from our API Definition.

package api

type ConsoleLine struct {
	Type    ConsoleLineType `json:"type,omitempty"`
	Message string          `json:"message,omitempty"`
}
