// This file was auto-generated by Fern from our API Definition.

package api

// CreateSourceRequest is an in-lined request used by the CreateSource endpoint.
type CreateSourceRequest struct {
	// A unique name for the source <span style="white-space: nowrap">`<= 155 characters`</span>
	Name string `json:"name,omitempty"`
}
