// This file was auto-generated by Fern from our API Definition.

package api

type CreateRequestBulkRetryRequestQueryRejectionCauseCreateRequestBulkRetryRequestQueryRejectionCause struct {
	Gt       *RequestRejectionCause `json:"gt,omitempty"`
	Gte      *RequestRejectionCause `json:"gte,omitempty"`
	Le       *RequestRejectionCause `json:"le,omitempty"`
	Lte      *RequestRejectionCause `json:"lte,omitempty"`
	Any      *bool                  `json:"any,omitempty"`
	Contains *RequestRejectionCause `json:"contains,omitempty"`
}
