// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	strconv "strconv"
)

type CreateRequestBulkRetryRequestQueryStatus uint8

const (
	CreateRequestBulkRetryRequestQueryStatusAccepted CreateRequestBulkRetryRequestQueryStatus = iota + 1
	CreateRequestBulkRetryRequestQueryStatusRejected
)

func (c CreateRequestBulkRetryRequestQueryStatus) String() string {
	switch c {
	default:
		return strconv.Itoa(int(c))
	case CreateRequestBulkRetryRequestQueryStatusAccepted:
		return "accepted"
	case CreateRequestBulkRetryRequestQueryStatusRejected:
		return "rejected"
	}
}

func (c CreateRequestBulkRetryRequestQueryStatus) MarshalJSON() ([]byte, error) {
	return []byte(fmt.Sprintf("%q", c.String())), nil
}

func (c *CreateRequestBulkRetryRequestQueryStatus) UnmarshalJSON(data []byte) error {
	var raw string
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	switch raw {
	case "accepted":
		value := CreateRequestBulkRetryRequestQueryStatusAccepted
		*c = value
	case "rejected":
		value := CreateRequestBulkRetryRequestQueryStatusRejected
		*c = value
	}
	return nil
}
