// This file was auto-generated by Fern from our API Definition.

package api

type CreateIgnoredEventBulkRetryRequest struct {
	// Filter by the bulk retry ignored event query object
	Query *CreateIgnoredEventBulkRetryRequestQuery `json:"query,omitempty"`
}
