// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
)

// Delivery issue
type DeliveryIssue struct {
	// Issue ID
	Id string `json:"id,omitempty"`
	// ID of the workspace
	TeamId string      `json:"team_id,omitempty"`
	Status IssueStatus `json:"status,omitempty"`
	// ISO timestamp for when the issue was last opened
	OpenedAt string `json:"opened_at,omitempty"`
	// ISO timestamp for when the issue was first opened
	FirstSeenAt string `json:"first_seen_at,omitempty"`
	// ISO timestamp for when the issue last occured
	LastSeenAt string `json:"last_seen_at,omitempty"`
	// ID of the team member who last updated the issue status
	LastUpdatedBy *string `json:"last_updated_by,omitempty"`
	// ISO timestamp for when the issue was dismissed
	DismissedAt    *string `json:"dismissed_at,omitempty"`
	AutoResolvedAt *string `json:"auto_resolved_at,omitempty"`
	MergedWith     *string `json:"merged_with,omitempty"`
	// ISO timestamp for when the issue was last updated
	UpdatedAt string `json:"updated_at,omitempty"`
	// ISO timestamp for when the issue was created
	CreatedAt       string                        `json:"created_at,omitempty"`
	AggregationKeys *DeliveryIssueAggregationKeys `json:"aggregation_keys,omitempty"`
	Reference       *DeliveryIssueReference       `json:"reference,omitempty"`
	type_           string
}

func (d *DeliveryIssue) Type() string {
	return d.type_
}

func (d *DeliveryIssue) UnmarshalJSON(data []byte) error {
	type unmarshaler DeliveryIssue
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeliveryIssue(value)
	d.type_ = "delivery"
	return nil
}

func (d *DeliveryIssue) MarshalJSON() ([]byte, error) {
	type embed DeliveryIssue
	var marshaler = struct {
		embed
		Type string `json:"type,omitempty"`
	}{
		embed: embed(*d),
		Type:  "delivery",
	}
	return json.Marshal(marshaler)
}
