// This file was auto-generated by Fern from our API Definition.

package api

import (
	core "github.com/hookdeck/hookdeck-go-sdk/core"
	time "time"
)

type DestinationCreateRequest struct {
	// Name for the destination <span style="white-space: nowrap">`<= 155 characters`</span>
	Name string `json:"name"`
	// Description for the destination
	Description *core.Optional[string] `json:"description,omitempty"`
	// Endpoint of the destination
	Url *core.Optional[string] `json:"url,omitempty"`
	// Path for the CLI destination
	CliPath *core.Optional[string] `json:"cli_path,omitempty"`
	// Period to rate limit attempts
	RateLimitPeriod *core.Optional[DestinationCreateRequestRateLimitPeriod] `json:"rate_limit_period,omitempty"`
	// Limit event attempts to receive per period
	RateLimit              *core.Optional[int]                         `json:"rate_limit,omitempty"`
	HttpMethod             *core.Optional[DestinationHttpMethod]       `json:"http_method,omitempty"`
	AuthMethod             *core.Optional[DestinationAuthMethodConfig] `json:"auth_method,omitempty"`
	PathForwardingDisabled *core.Optional[bool]                        `json:"path_forwarding_disabled,omitempty"`
}

type DestinationListRequest struct {
	Id         *string                    `json:"-"`
	Name       *string                    `json:"-"`
	Archived   *bool                      `json:"-"`
	ArchivedAt *time.Time                 `json:"-"`
	Url        *string                    `json:"-"`
	CliPath    *string                    `json:"-"`
	OrderBy    *string                    `json:"-"`
	Dir        *DestinationListRequestDir `json:"-"`
	Limit      *int                       `json:"-"`
	Next       *string                    `json:"-"`
	Prev       *string                    `json:"-"`
}

type DestinationUpdateRequest struct {
	// Name for the destination <span style="white-space: nowrap">`<= 155 characters`</span>
	Name *core.Optional[string] `json:"name,omitempty"`
	// Description for the destination
	Description *core.Optional[string] `json:"description,omitempty"`
	// Endpoint of the destination
	Url *core.Optional[string] `json:"url,omitempty"`
	// Path for the CLI destination
	CliPath *core.Optional[string] `json:"cli_path,omitempty"`
	// Period to rate limit attempts
	RateLimitPeriod *core.Optional[DestinationUpdateRequestRateLimitPeriod] `json:"rate_limit_period,omitempty"`
	// Limit event attempts to receive per period
	RateLimit              *core.Optional[int]                         `json:"rate_limit,omitempty"`
	HttpMethod             *core.Optional[DestinationHttpMethod]       `json:"http_method,omitempty"`
	AuthMethod             *core.Optional[DestinationAuthMethodConfig] `json:"auth_method,omitempty"`
	PathForwardingDisabled *core.Optional[bool]                        `json:"path_forwarding_disabled,omitempty"`
}

type DestinationUpsertRequest struct {
	// Name for the destination <span style="white-space: nowrap">`<= 155 characters`</span>
	Name string `json:"name"`
	// Description for the destination
	Description *core.Optional[string] `json:"description,omitempty"`
	// Endpoint of the destination
	Url *core.Optional[string] `json:"url,omitempty"`
	// Path for the CLI destination
	CliPath *core.Optional[string] `json:"cli_path,omitempty"`
	// Period to rate limit attempts
	RateLimitPeriod *core.Optional[DestinationUpsertRequestRateLimitPeriod] `json:"rate_limit_period,omitempty"`
	// Limit event attempts to receive per period
	RateLimit              *core.Optional[int]                         `json:"rate_limit,omitempty"`
	HttpMethod             *core.Optional[DestinationHttpMethod]       `json:"http_method,omitempty"`
	AuthMethod             *core.Optional[DestinationAuthMethodConfig] `json:"auth_method,omitempty"`
	PathForwardingDisabled *core.Optional[bool]                        `json:"path_forwarding_disabled,omitempty"`
}
