// This file was auto-generated by Fern from our API Definition.

package api

// Associated [Destination](#destination-object) object
type Destination struct {
	// ID of the destination
	Id string `json:"id"`
	// A unique, human-friendly name for the destination
	Name string `json:"name"`
	// ID of the workspace
	TeamId                 string `json:"team_id"`
	PathForwardingDisabled *bool  `json:"path_forwarding_disabled,omitempty"`
	// HTTP endpoint of the destination
	Url *string `json:"url,omitempty"`
	// Path for the CLI destination
	CliPath *string `json:"cli_path,omitempty"`
	// Limit event attempts to receive per period. Max value is workspace plan's max attempts thoughput.
	RateLimit       *int                        `json:"rate_limit,omitempty"`
	RateLimitPeriod *DestinationRateLimitPeriod `json:"rate_limit_period,omitempty"`
	// Date the destination was archived
	ArchivedAt *string `json:"archived_at,omitempty"`
	// Date the destination was last updated
	UpdatedAt string `json:"updated_at"`
	// Date the destination was created
	CreatedAt string `json:"created_at"`
}
