// This file was auto-generated by Fern from our API Definition.

// A transformation represents JavaScript code that will be executed on a connection's requests. Transformations are applied to connections using Rules.
package api
