// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	strconv "strconv"
)

type GetRequestsRequestDirGetRequestsRequestDir uint8

const (
	GetRequestsRequestDirGetRequestsRequestDirAsc GetRequestsRequestDirGetRequestsRequestDir = iota + 1
	GetRequestsRequestDirGetRequestsRequestDirDesc
)

func (g GetRequestsRequestDirGetRequestsRequestDir) String() string {
	switch g {
	default:
		return strconv.Itoa(int(g))
	case GetRequestsRequestDirGetRequestsRequestDirAsc:
		return "asc"
	case GetRequestsRequestDirGetRequestsRequestDirDesc:
		return "desc"
	}
}

func (g GetRequestsRequestDirGetRequestsRequestDir) MarshalJSON() ([]byte, error) {
	return []byte(fmt.Sprintf("%q", g.String())), nil
}

func (g *GetRequestsRequestDirGetRequestsRequestDir) UnmarshalJSON(data []byte) error {
	var raw string
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	switch raw {
	case "asc":
		value := GetRequestsRequestDirGetRequestsRequestDirAsc
		*g = value
	case "desc":
		value := GetRequestsRequestDirGetRequestsRequestDirDesc
		*g = value
	}
	return nil
}
