// This file was auto-generated by Fern from our API Definition.

package api

// GetRulesetsRequest is an in-lined request used by the GetRulesets endpoint.
type GetRulesetsRequest struct {
	Id         *string                                     `json:"-"`
	Name       *string                                     `json:"-"`
	Archived   *bool                                       `json:"-"`
	ArchivedAt *string                                     `json:"-"`
	OrderBy    *string                                     `json:"-"`
	Dir        *GetRulesetsRequestDirGetRulesetsRequestDir `json:"-"`
	Limit      *int                                        `json:"-"`
	Next       *string                                     `json:"-"`
	Prev       *string                                     `json:"-"`
}
