// This file was auto-generated by Fern from our API Definition.

package api

// GetTransformationExecutionsRequest is an in-lined request used by the GetTransformationExecutions endpoint.
type GetTransformationExecutionsRequest struct {
	LogLevel  *GetTransformationExecutionsRequestLogLevelGetTransformationExecutionsRequestLogLevel `json:"-"`
	WebhookId *string                                                                               `json:"-"`
	IssueId   *string                                                                               `json:"-"`
	CreatedAt *string                                                                               `json:"-"`
	OrderBy   *string                                                                               `json:"-"`
	Dir       *GetTransformationExecutionsRequestDirGetTransformationExecutionsRequestDir           `json:"-"`
	Limit     *int                                                                                  `json:"-"`
	Next      *string                                                                               `json:"-"`
	Prev      *string                                                                               `json:"-"`
}
