// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	strconv "strconv"
)

type GetIssueCountRequestOrderByGetIssueCountRequestOrderBy uint8

const (
	GetIssueCountRequestOrderByGetIssueCountRequestOrderByCreatedAt GetIssueCountRequestOrderByGetIssueCountRequestOrderBy = iota + 1
	GetIssueCountRequestOrderByGetIssueCountRequestOrderByFirstSeenAt
	GetIssueCountRequestOrderByGetIssueCountRequestOrderByLastSeenAt
	GetIssueCountRequestOrderByGetIssueCountRequestOrderByOpenedAt
	GetIssueCountRequestOrderByGetIssueCountRequestOrderByStatus
)

func (g GetIssueCountRequestOrderByGetIssueCountRequestOrderBy) String() string {
	switch g {
	default:
		return strconv.Itoa(int(g))
	case GetIssueCountRequestOrderByGetIssueCountRequestOrderByCreatedAt:
		return "created_at"
	case GetIssueCountRequestOrderByGetIssueCountRequestOrderByFirstSeenAt:
		return "first_seen_at"
	case GetIssueCountRequestOrderByGetIssueCountRequestOrderByLastSeenAt:
		return "last_seen_at"
	case GetIssueCountRequestOrderByGetIssueCountRequestOrderByOpenedAt:
		return "opened_at"
	case GetIssueCountRequestOrderByGetIssueCountRequestOrderByStatus:
		return "status"
	}
}

func (g GetIssueCountRequestOrderByGetIssueCountRequestOrderBy) MarshalJSON() ([]byte, error) {
	return []byte(fmt.Sprintf("%q", g.String())), nil
}

func (g *GetIssueCountRequestOrderByGetIssueCountRequestOrderBy) UnmarshalJSON(data []byte) error {
	var raw string
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	switch raw {
	case "created_at":
		value := GetIssueCountRequestOrderByGetIssueCountRequestOrderByCreatedAt
		*g = value
	case "first_seen_at":
		value := GetIssueCountRequestOrderByGetIssueCountRequestOrderByFirstSeenAt
		*g = value
	case "last_seen_at":
		value := GetIssueCountRequestOrderByGetIssueCountRequestOrderByLastSeenAt
		*g = value
	case "opened_at":
		value := GetIssueCountRequestOrderByGetIssueCountRequestOrderByOpenedAt
		*g = value
	case "status":
		value := GetIssueCountRequestOrderByGetIssueCountRequestOrderByStatus
		*g = value
	}
	return nil
}
