// This file was auto-generated by Fern from our API Definition.

package api

// GetDestinationsRequest is an in-lined request used by the GetDestinations endpoint.
type GetDestinationsRequest struct {
	Id         *string                                             `json:"-"`
	Name       *string                                             `json:"-"`
	Archived   *bool                                               `json:"-"`
	ArchivedAt *string                                             `json:"-"`
	Url        *string                                             `json:"-"`
	CliPath    *string                                             `json:"-"`
	OrderBy    *string                                             `json:"-"`
	Dir        *GetDestinationsRequestDirGetDestinationsRequestDir `json:"-"`
	Limit      *int                                                `json:"-"`
	Next       *string                                             `json:"-"`
	Prev       *string                                             `json:"-"`
}
