// This file was auto-generated by Fern from our API Definition.

package api

// GetRequestBulkRetriesRequest is an in-lined request used by the GetRequestBulkRetries endpoint.
type GetRequestBulkRetriesRequest struct {
	CancelledAt       *string                                                         `json:"-"`
	CompletedAt       *string                                                         `json:"-"`
	CreatedAt         *string                                                         `json:"-"`
	Id                *string                                                         `json:"-"`
	InProgress        *bool                                                           `json:"-"`
	QueryPartialMatch *bool                                                           `json:"-"`
	OrderBy           *string                                                         `json:"-"`
	Dir               *GetRequestBulkRetriesRequestDirGetRequestBulkRetriesRequestDir `json:"-"`
	Limit             *int                                                            `json:"-"`
	Next              *string                                                         `json:"-"`
	Prev              *string                                                         `json:"-"`
}
