// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	strconv "strconv"
)

// Issue type
type GetIssueCountRequestTypeGetIssueCountRequestType uint8

const (
	GetIssueCountRequestTypeGetIssueCountRequestTypeDelivery GetIssueCountRequestTypeGetIssueCountRequestType = iota + 1
	GetIssueCountRequestTypeGetIssueCountRequestTypeTransformation
	GetIssueCountRequestTypeGetIssueCountRequestTypeBackpressure
)

func (g GetIssueCountRequestTypeGetIssueCountRequestType) String() string {
	switch g {
	default:
		return strconv.Itoa(int(g))
	case GetIssueCountRequestTypeGetIssueCountRequestTypeDelivery:
		return "delivery"
	case GetIssueCountRequestTypeGetIssueCountRequestTypeTransformation:
		return "transformation"
	case GetIssueCountRequestTypeGetIssueCountRequestTypeBackpressure:
		return "backpressure"
	}
}

func (g GetIssueCountRequestTypeGetIssueCountRequestType) MarshalJSON() ([]byte, error) {
	return []byte(fmt.Sprintf("%q", g.String())), nil
}

func (g *GetIssueCountRequestTypeGetIssueCountRequestType) UnmarshalJSON(data []byte) error {
	var raw string
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	switch raw {
	case "delivery":
		value := GetIssueCountRequestTypeGetIssueCountRequestTypeDelivery
		*g = value
	case "transformation":
		value := GetIssueCountRequestTypeGetIssueCountRequestTypeTransformation
		*g = value
	case "backpressure":
		value := GetIssueCountRequestTypeGetIssueCountRequestTypeBackpressure
		*g = value
	}
	return nil
}
