// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	strconv "strconv"
)

type GetRequestIgnoredEventsRequestDirGetRequestIgnoredEventsRequestDir uint8

const (
	GetRequestIgnoredEventsRequestDirGetRequestIgnoredEventsRequestDirAsc GetRequestIgnoredEventsRequestDirGetRequestIgnoredEventsRequestDir = iota + 1
	GetRequestIgnoredEventsRequestDirGetRequestIgnoredEventsRequestDirDesc
)

func (g GetRequestIgnoredEventsRequestDirGetRequestIgnoredEventsRequestDir) String() string {
	switch g {
	default:
		return strconv.Itoa(int(g))
	case GetRequestIgnoredEventsRequestDirGetRequestIgnoredEventsRequestDirAsc:
		return "asc"
	case GetRequestIgnoredEventsRequestDirGetRequestIgnoredEventsRequestDirDesc:
		return "desc"
	}
}

func (g GetRequestIgnoredEventsRequestDirGetRequestIgnoredEventsRequestDir) MarshalJSON() ([]byte, error) {
	return []byte(fmt.Sprintf("%q", g.String())), nil
}

func (g *GetRequestIgnoredEventsRequestDirGetRequestIgnoredEventsRequestDir) UnmarshalJSON(data []byte) error {
	var raw string
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	switch raw {
	case "asc":
		value := GetRequestIgnoredEventsRequestDirGetRequestIgnoredEventsRequestDirAsc
		*g = value
	case "desc":
		value := GetRequestIgnoredEventsRequestDirGetRequestIgnoredEventsRequestDirDesc
		*g = value
	}
	return nil
}
