// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	strconv "strconv"
)

type GetIssuesRequestDirGetIssuesRequestDir uint8

const (
	GetIssuesRequestDirGetIssuesRequestDirAsc GetIssuesRequestDirGetIssuesRequestDir = iota + 1
	GetIssuesRequestDirGetIssuesRequestDirDesc
)

func (g GetIssuesRequestDirGetIssuesRequestDir) String() string {
	switch g {
	default:
		return strconv.Itoa(int(g))
	case GetIssuesRequestDirGetIssuesRequestDirAsc:
		return "asc"
	case GetIssuesRequestDirGetIssuesRequestDirDesc:
		return "desc"
	}
}

func (g GetIssuesRequestDirGetIssuesRequestDir) MarshalJSON() ([]byte, error) {
	return []byte(fmt.Sprintf("%q", g.String())), nil
}

func (g *GetIssuesRequestDirGetIssuesRequestDir) UnmarshalJSON(data []byte) error {
	var raw string
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	switch raw {
	case "asc":
		value := GetIssuesRequestDirGetIssuesRequestDirAsc
		*g = value
	case "desc":
		value := GetIssuesRequestDirGetIssuesRequestDirDesc
		*g = value
	}
	return nil
}
