// This file was auto-generated by Fern from our API Definition.

package api

// GetConnectionsRequest is an in-lined request used by the GetConnections endpoint.
type GetConnectionsRequest struct {
	Id            *string                                           `json:"-"`
	Name          *string                                           `json:"-"`
	DestinationId *string                                           `json:"-"`
	SourceId      *string                                           `json:"-"`
	Archived      *bool                                             `json:"-"`
	ArchivedAt    *string                                           `json:"-"`
	FullName      *string                                           `json:"-"`
	PausedAt      *string                                           `json:"-"`
	OrderBy       *string                                           `json:"-"`
	Dir           *GetConnectionsRequestDirGetConnectionsRequestDir `json:"-"`
	Limit         *int                                              `json:"-"`
	Next          *string                                           `json:"-"`
	Prev          *string                                           `json:"-"`
}
