// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	strconv "strconv"
)

type GetRulesetsRequestDirGetRulesetsRequestDir uint8

const (
	GetRulesetsRequestDirGetRulesetsRequestDirAsc GetRulesetsRequestDirGetRulesetsRequestDir = iota + 1
	GetRulesetsRequestDirGetRulesetsRequestDirDesc
)

func (g GetRulesetsRequestDirGetRulesetsRequestDir) String() string {
	switch g {
	default:
		return strconv.Itoa(int(g))
	case GetRulesetsRequestDirGetRulesetsRequestDirAsc:
		return "asc"
	case GetRulesetsRequestDirGetRulesetsRequestDirDesc:
		return "desc"
	}
}

func (g GetRulesetsRequestDirGetRulesetsRequestDir) MarshalJSON() ([]byte, error) {
	return []byte(fmt.Sprintf("%q", g.String())), nil
}

func (g *GetRulesetsRequestDirGetRulesetsRequestDir) UnmarshalJSON(data []byte) error {
	var raw string
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	switch raw {
	case "asc":
		value := GetRulesetsRequestDirGetRulesetsRequestDirAsc
		*g = value
	case "desc":
		value := GetRulesetsRequestDirGetRulesetsRequestDirDesc
		*g = value
	}
	return nil
}
