// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	strconv "strconv"
)

type HmacIntegrationConfigsEncoding uint8

const (
	HmacIntegrationConfigsEncodingBase64 HmacIntegrationConfigsEncoding = iota + 1
	HmacIntegrationConfigsEncodingHex
)

func (h HmacIntegrationConfigsEncoding) String() string {
	switch h {
	default:
		return strconv.Itoa(int(h))
	case HmacIntegrationConfigsEncodingBase64:
		return "base64"
	case HmacIntegrationConfigsEncodingHex:
		return "hex"
	}
}

func (h HmacIntegrationConfigsEncoding) MarshalJSON() ([]byte, error) {
	return []byte(fmt.Sprintf("%q", h.String())), nil
}

func (h *HmacIntegrationConfigsEncoding) UnmarshalJSON(data []byte) error {
	var raw string
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	switch raw {
	case "base64":
		value := HmacIntegrationConfigsEncodingBase64
		*h = value
	case "hex":
		value := HmacIntegrationConfigsEncodingHex
		*h = value
	}
	return nil
}
