// This file was auto-generated by Fern from our API Definition.

package api

type HmacIntegrationConfigs struct {
	WebhookSecretKey string                         `json:"webhook_secret_key,omitempty"`
	Algorithm        HmacAlgorithms                 `json:"algorithm,omitempty"`
	HeaderKey        string                         `json:"header_key,omitempty"`
	Encoding         HmacIntegrationConfigsEncoding `json:"encoding,omitempty"`
}
