// This file was auto-generated by Fern from our API Definition.

package api

type IgnoredEvent struct {
	Id        string            `json:"id,omitempty"`
	TeamId    string            `json:"team_id,omitempty"`
	WebhookId string            `json:"webhook_id,omitempty"`
	Cause     IgnoredEventCause `json:"cause,omitempty"`
	RequestId string            `json:"request_id,omitempty"`
	Meta      *IgnoredEventMeta `json:"meta,omitempty"`
	UpdatedAt string            `json:"updated_at,omitempty"`
	CreatedAt string            `json:"created_at,omitempty"`
}
