// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	strconv "strconv"
)

type IntegrationFeature uint8

const (
	IntegrationFeatureVerification IntegrationFeature = iota + 1
	IntegrationFeatureHandshake
	IntegrationFeaturePolling
)

func (i IntegrationFeature) String() string {
	switch i {
	default:
		return strconv.Itoa(int(i))
	case IntegrationFeatureVerification:
		return "VERIFICATION"
	case IntegrationFeatureHandshake:
		return "HANDSHAKE"
	case IntegrationFeaturePolling:
		return "POLLING"
	}
}

func (i IntegrationFeature) MarshalJSON() ([]byte, error) {
	return []byte(fmt.Sprintf("%q", i.String())), nil
}

func (i *IntegrationFeature) UnmarshalJSON(data []byte) error {
	var raw string
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	switch raw {
	case "VERIFICATION":
		value := IntegrationFeatureVerification
		*i = value
	case "HANDSHAKE":
		value := IntegrationFeatureHandshake
		*i = value
	case "POLLING":
		value := IntegrationFeaturePolling
		*i = value
	}
	return nil
}
