// This file was auto-generated by Fern from our API Definition.

package api

import (
	core "github.com/hookdeck/hookdeck-go-sdk/core"
)

// Optional initializes an optional field.
func Optional[T any](value T) *core.Optional[T] {
	return &core.Optional[T]{
		Value: value,
	}
}

// Null initializes an optional field that will be sent as
// an explicit null value.
func Null[T any]() *core.Optional[T] {
	return &core.Optional[T]{
		Null: true,
	}
}

// OptionalOrNull initializes an optional field, setting the value
// to an explicit null if the value is nil.
func OptionalOrNull[T any](value *T) *core.Optional[T] {
	if value == nil {
		return Null[T]()
	}
	return Optional(*value)
}
