// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	strconv "strconv"
)

type OrderByDirection uint8

const (
	OrderByDirectionasc OrderByDirection = iota + 1
	OrderByDirectiondesc
	OrderByDirectionASC
	OrderByDirectionDESC
)

func (o OrderByDirection) String() string {
	switch o {
	default:
		return strconv.Itoa(int(o))
	case OrderByDirectionasc:
		return "asc"
	case OrderByDirectiondesc:
		return "desc"
	case OrderByDirectionASC:
		return "ASC"
	case OrderByDirectionDESC:
		return "DESC"
	}
}

func (o OrderByDirection) MarshalJSON() ([]byte, error) {
	return []byte(fmt.Sprintf("%q", o.String())), nil
}

func (o *OrderByDirection) UnmarshalJSON(data []byte) error {
	var raw string
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	switch raw {
	case "asc":
		value := OrderByDirectionasc
		*o = value
	case "desc":
		value := OrderByDirectiondesc
		*o = value
	case "ASC":
		value := OrderByDirectionASC
		*o = value
	case "DESC":
		value := OrderByDirectionDESC
		*o = value
	}
	return nil
}
