// This file was auto-generated by Fern from our API Definition.

package api

type Request struct {
	// ID of the request
	Id string `json:"id"`
	// ID of the workspace
	TeamId string `json:"team_id"`
	// Whether or not the request was verified when received
	Verified *bool `json:"verified,omitempty"`
	// ID of the request data
	OriginalEventDataId *string `json:"original_event_data_id,omitempty"`
	// Hash of the request data payload used to check for duplicates
	DuplicateHash *string `json:"duplicate_hash,omitempty"`
	// Count of duplicate hits found
	DuplicateHits  *int                   `json:"duplicate_hits,omitempty"`
	RejectionCause *RequestRejectionCause `json:"rejection_cause,omitempty"`
	// The priority attributed to the request when received
	IngestPriority *RequestIngestPriority `json:"ingest_priority,omitempty"`
	// The time the request was originally received
	IngestedAt   *string `json:"ingested_at,omitempty"`
	IngestedAtId *string `json:"ingested_at_id,omitempty"`
	// ID of the associated source
	SourceId string `json:"source_id"`
	// The count of events created from this request (CLI events not included)
	EventsCount *int `json:"events_count,omitempty"`
	// The count of CLI events created from this request
	CliEventsCount *int         `json:"cli_events_count,omitempty"`
	IgnoredCount   *int         `json:"ignored_count,omitempty"`
	Data           *RequestData `json:"data,omitempty"`
	// Date the event was last updated
	UpdatedAt string `json:"updated_at"`
	// Date the event was created
	CreatedAt string `json:"created_at"`
}
