// This file was auto-generated by Fern from our API Definition.

package api

import (
	fmt "fmt"
	time "time"
)

type RequestListRequest struct {
	Id             *string                    `json:"-"`
	Status         *RequestListRequestStatus  `json:"-"`
	RejectionCause *RequestRejectionCause     `json:"-"`
	SourceId       *string                    `json:"-"`
	Verified       *bool                      `json:"-"`
	SearchTerm     *string                    `json:"-"`
	Headers        *string                    `json:"-"`
	Body           *string                    `json:"-"`
	ParsedQuery    *string                    `json:"-"`
	Path           *string                    `json:"-"`
	IgnoredCount   *int                       `json:"-"`
	EventsCount    *int                       `json:"-"`
	IngestedAt     *time.Time                 `json:"-"`
	BulkRetryId    *string                    `json:"-"`
	Include        *string                    `json:"-"`
	OrderBy        *RequestListRequestOrderBy `json:"-"`
	Dir            *RequestListRequestDir     `json:"-"`
	Limit          *int                       `json:"-"`
	Next           *string                    `json:"-"`
	Prev           *string                    `json:"-"`
}

type RequestListEventRequest struct {
	Id             *string                         `json:"-"`
	Status         *EventStatus                    `json:"-"`
	WebhookId      *string                         `json:"-"`
	DestinationId  *string                         `json:"-"`
	SourceId       *string                         `json:"-"`
	Attempts       *int                            `json:"-"`
	ResponseStatus *int                            `json:"-"`
	SuccessfulAt   *time.Time                      `json:"-"`
	CreatedAt      *time.Time                      `json:"-"`
	ErrorCode      *AttemptErrorCodes              `json:"-"`
	CliId          *string                         `json:"-"`
	LastAttemptAt  *time.Time                      `json:"-"`
	SearchTerm     *string                         `json:"-"`
	Headers        *string                         `json:"-"`
	Body           *string                         `json:"-"`
	ParsedQuery    *string                         `json:"-"`
	Path           *string                         `json:"-"`
	CliUserId      *string                         `json:"-"`
	IssueId        *string                         `json:"-"`
	EventDataId    *string                         `json:"-"`
	BulkRetryId    *string                         `json:"-"`
	Include        *string                         `json:"-"`
	OrderBy        *RequestListEventRequestOrderBy `json:"-"`
	Dir            *RequestListEventRequestDir     `json:"-"`
	Limit          *int                            `json:"-"`
	Next           *string                         `json:"-"`
	Prev           *string                         `json:"-"`
}

type RequestListIgnoredEventRequest struct {
	Id      *string                                `json:"-"`
	OrderBy *RequestListIgnoredEventRequestOrderBy `json:"-"`
	Dir     *RequestListIgnoredEventRequestDir     `json:"-"`
	Limit   *int                                   `json:"-"`
	Next    *string                                `json:"-"`
	Prev    *string                                `json:"-"`
}

type RequestRetryRequest struct {
	// Subset of webhook_ids to re-run the event logic on. Useful to retry only specific ignored_events
	WebhookIds []string `json:"webhook_ids,omitempty"`
}

// Sort direction
type RequestListEventRequestDir string

const (
	RequestListEventRequestDirAsc  RequestListEventRequestDir = "asc"
	RequestListEventRequestDirDesc RequestListEventRequestDir = "desc"
)

func NewRequestListEventRequestDirFromString(s string) (RequestListEventRequestDir, error) {
	switch s {
	case "asc":
		return RequestListEventRequestDirAsc, nil
	case "desc":
		return RequestListEventRequestDirDesc, nil
	}
	var t RequestListEventRequestDir
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r RequestListEventRequestDir) Ptr() *RequestListEventRequestDir {
	return &r
}

// Sort key
type RequestListEventRequestOrderBy string

const (
	RequestListEventRequestOrderByLastAttemptAt RequestListEventRequestOrderBy = "last_attempt_at"
	RequestListEventRequestOrderByCreatedAt     RequestListEventRequestOrderBy = "created_at"
)

func NewRequestListEventRequestOrderByFromString(s string) (RequestListEventRequestOrderBy, error) {
	switch s {
	case "last_attempt_at":
		return RequestListEventRequestOrderByLastAttemptAt, nil
	case "created_at":
		return RequestListEventRequestOrderByCreatedAt, nil
	}
	var t RequestListEventRequestOrderBy
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r RequestListEventRequestOrderBy) Ptr() *RequestListEventRequestOrderBy {
	return &r
}

type RequestListIgnoredEventRequestDir string

const (
	RequestListIgnoredEventRequestDirAsc  RequestListIgnoredEventRequestDir = "asc"
	RequestListIgnoredEventRequestDirDesc RequestListIgnoredEventRequestDir = "desc"
)

func NewRequestListIgnoredEventRequestDirFromString(s string) (RequestListIgnoredEventRequestDir, error) {
	switch s {
	case "asc":
		return RequestListIgnoredEventRequestDirAsc, nil
	case "desc":
		return RequestListIgnoredEventRequestDirDesc, nil
	}
	var t RequestListIgnoredEventRequestDir
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r RequestListIgnoredEventRequestDir) Ptr() *RequestListIgnoredEventRequestDir {
	return &r
}

type RequestListIgnoredEventRequestOrderBy string

const (
	RequestListIgnoredEventRequestOrderByCreatedAt RequestListIgnoredEventRequestOrderBy = "created_at"
)

func NewRequestListIgnoredEventRequestOrderByFromString(s string) (RequestListIgnoredEventRequestOrderBy, error) {
	switch s {
	case "created_at":
		return RequestListIgnoredEventRequestOrderByCreatedAt, nil
	}
	var t RequestListIgnoredEventRequestOrderBy
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r RequestListIgnoredEventRequestOrderBy) Ptr() *RequestListIgnoredEventRequestOrderBy {
	return &r
}

// Sort direction
type RequestListRequestDir string

const (
	RequestListRequestDirAsc  RequestListRequestDir = "asc"
	RequestListRequestDirDesc RequestListRequestDir = "desc"
)

func NewRequestListRequestDirFromString(s string) (RequestListRequestDir, error) {
	switch s {
	case "asc":
		return RequestListRequestDirAsc, nil
	case "desc":
		return RequestListRequestDirDesc, nil
	}
	var t RequestListRequestDir
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r RequestListRequestDir) Ptr() *RequestListRequestDir {
	return &r
}

// Sort key
type RequestListRequestOrderBy string

const (
	RequestListRequestOrderByIngestedAt RequestListRequestOrderBy = "ingested_at"
	RequestListRequestOrderByCreatedAt  RequestListRequestOrderBy = "created_at"
)

func NewRequestListRequestOrderByFromString(s string) (RequestListRequestOrderBy, error) {
	switch s {
	case "ingested_at":
		return RequestListRequestOrderByIngestedAt, nil
	case "created_at":
		return RequestListRequestOrderByCreatedAt, nil
	}
	var t RequestListRequestOrderBy
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r RequestListRequestOrderBy) Ptr() *RequestListRequestOrderBy {
	return &r
}

// Filter by status
type RequestListRequestStatus string

const (
	RequestListRequestStatusAccepted RequestListRequestStatus = "accepted"
	RequestListRequestStatusRejected RequestListRequestStatus = "rejected"
)

func NewRequestListRequestStatusFromString(s string) (RequestListRequestStatus, error) {
	switch s {
	case "accepted":
		return RequestListRequestStatusAccepted, nil
	case "rejected":
		return RequestListRequestStatusRejected, nil
	}
	var t RequestListRequestStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r RequestListRequestStatus) Ptr() *RequestListRequestStatus {
	return &r
}
