// This file was auto-generated by Fern from our API Definition.

package api

// Associated [Ruleset](#ruleset-object) object
type Ruleset struct {
	// ID of the ruleset
	Id string `json:"id"`
	// A unique name for the ruleset
	Name string `json:"name"`
	// ID of the workspace
	TeamId string `json:"team_id"`
	// Array of rules to apply
	Rules []*Rule `json:"rules,omitempty"`
	// Default ruleset of Workspace
	IsTeamDefault bool `json:"is_team_default"`
	// Date the ruleset was archived
	ArchivedAt *string `json:"archived_at,omitempty"`
	// Date the ruleset was last updated
	UpdatedAt string `json:"updated_at"`
	// Date the ruleset was created
	CreatedAt string `json:"created_at"`
}
