// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	strconv "strconv"
)

type ShopifyIntegrationConfigsRateLimitPeriod uint8

const (
	ShopifyIntegrationConfigsRateLimitPeriodMinute ShopifyIntegrationConfigsRateLimitPeriod = iota + 1
	ShopifyIntegrationConfigsRateLimitPeriodSecond
)

func (s ShopifyIntegrationConfigsRateLimitPeriod) String() string {
	switch s {
	default:
		return strconv.Itoa(int(s))
	case ShopifyIntegrationConfigsRateLimitPeriodMinute:
		return "minute"
	case ShopifyIntegrationConfigsRateLimitPeriodSecond:
		return "second"
	}
}

func (s ShopifyIntegrationConfigsRateLimitPeriod) MarshalJSON() ([]byte, error) {
	return []byte(fmt.Sprintf("%q", s.String())), nil
}

func (s *ShopifyIntegrationConfigsRateLimitPeriod) UnmarshalJSON(data []byte) error {
	var raw string
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	switch raw {
	case "minute":
		value := ShopifyIntegrationConfigsRateLimitPeriodMinute
		*s = value
	case "second":
		value := ShopifyIntegrationConfigsRateLimitPeriodSecond
		*s = value
	}
	return nil
}
