// This file was auto-generated by Fern from our API Definition.

package api

import (
	core "github.com/hookdeck/hookdeck-go-sdk/core"
	time "time"
)

type TransformationCreateRequest struct {
	// A unique, human-friendly name for the transformation <span style="white-space: nowrap">`<= 155 characters`</span>
	Name string `json:"name"`
	// JavaScript code to be executed as string
	Code string `json:"code"`
	// Key-value environment variables to be passed to the transformation
	Env map[string]*TransformationCreateRequestEnvValue `json:"env,omitempty"`
}

type TransformationListRequest struct {
	Id      *string                       `json:"-"`
	Name    *string                       `json:"-"`
	OrderBy *string                       `json:"-"`
	Dir     *TransformationListRequestDir `json:"-"`
	Limit   *int                          `json:"-"`
	Next    *string                       `json:"-"`
	Prev    *string                       `json:"-"`
}

type TransformationListExecutionRequest struct {
	LogLevel  *TransformationListExecutionRequestLogLevel `json:"-"`
	WebhookId *string                                     `json:"-"`
	IssueId   *string                                     `json:"-"`
	CreatedAt *time.Time                                  `json:"-"`
	OrderBy   *string                                     `json:"-"`
	Dir       *TransformationListExecutionRequestDir      `json:"-"`
	Limit     *int                                        `json:"-"`
	Next      *string                                     `json:"-"`
	Prev      *string                                     `json:"-"`
}

type TransformationRunRequest struct {
	// Key-value environment variables to be passed to the transformation
	Env *core.Optional[TransformationRunRequestEnv] `json:"env,omitempty"`
	// ID of the connection to use for the execution `context`
	WebhookId *core.Optional[string] `json:"webhook_id,omitempty"`
	// JavaScript code to be executed
	Code *core.Optional[string] `json:"code,omitempty"`
	// Transformation ID
	TransformationId *core.Optional[string] `json:"transformation_id,omitempty"`
	// Request input to use for the transformation execution
	Request *core.Optional[TransformationRunRequestRequest] `json:"request,omitempty"`
	EventId *core.Optional[string]                          `json:"event_id,omitempty"`
}

type TransformationUpdateRequest struct {
	// A unique, human-friendly name for the transformation <span style="white-space: nowrap">`<= 155 characters`</span>
	Name *core.Optional[string] `json:"name,omitempty"`
	// JavaScript code to be executed
	Code *core.Optional[string] `json:"code,omitempty"`
	// Key-value environment variables to be passed to the transformation
	Env map[string]*TransformationUpdateRequestEnvValue `json:"env,omitempty"`
}

type TransformationUpsertRequest struct {
	// A unique, human-friendly name for the transformation <span style="white-space: nowrap">`<= 155 characters`</span>
	Name string `json:"name"`
	// JavaScript code to be executed as string
	Code string `json:"code"`
	// Key-value environment variables to be passed to the transformation
	Env map[string]*TransformationUpsertRequestEnvValue `json:"env,omitempty"`
}
