// This file was auto-generated by Fern from our API Definition.

package api

import (
	core "github.com/hookdeck/hookdeck-go-sdk/core"
	time "time"
)

type CreateTransformationRequest struct {
	// A unique, human-friendly name for the transformation <span style="white-space: nowrap">`<= 155 characters`</span>
	Name string `json:"name"`
	// JavaScript code to be executed as string
	Code string `json:"code"`
	// Key-value environment variables to be passed to the transformation
	Env map[string]*CreateTransformationRequestEnvValue `json:"env,omitempty"`
}

type GetTransformationExecutionsRequest struct {
	LogLevel  *GetTransformationExecutionsRequestLogLevel `json:"-"`
	WebhookId *string                                     `json:"-"`
	IssueId   *string                                     `json:"-"`
	CreatedAt *time.Time                                  `json:"-"`
	OrderBy   *string                                     `json:"-"`
	Dir       *GetTransformationExecutionsRequestDir      `json:"-"`
	Limit     *int                                        `json:"-"`
	Next      *string                                     `json:"-"`
	Prev      *string                                     `json:"-"`
}

type GetTransformationsRequest struct {
	Id      *string                       `json:"-"`
	Name    *string                       `json:"-"`
	OrderBy *string                       `json:"-"`
	Dir     *GetTransformationsRequestDir `json:"-"`
	Limit   *int                          `json:"-"`
	Next    *string                       `json:"-"`
	Prev    *string                       `json:"-"`
}

type TestTransformationRequest struct {
	// Key-value environment variables to be passed to the transformation
	Env *core.Optional[TestTransformationRequestEnv] `json:"env,omitempty"`
	// ID of the connection to use for the execution `context`
	WebhookId *core.Optional[string] `json:"webhook_id,omitempty"`
	// JavaScript code to be executed
	Code *core.Optional[string] `json:"code,omitempty"`
	// Transformation ID
	TransformationId *core.Optional[string] `json:"transformation_id,omitempty"`
	// Request input to use for the transformation execution
	Request *core.Optional[TestTransformationRequestRequest] `json:"request,omitempty"`
	EventId *core.Optional[string]                           `json:"event_id,omitempty"`
}

type UpdateTransformationRequest struct {
	// A unique, human-friendly name for the transformation <span style="white-space: nowrap">`<= 155 characters`</span>
	Name *core.Optional[string] `json:"name,omitempty"`
	// JavaScript code to be executed
	Code *core.Optional[string] `json:"code,omitempty"`
	// Key-value environment variables to be passed to the transformation
	Env map[string]*UpdateTransformationRequestEnvValue `json:"env,omitempty"`
}

type UpsertTransformationRequest struct {
	// A unique, human-friendly name for the transformation <span style="white-space: nowrap">`<= 155 characters`</span>
	Name string `json:"name"`
	// JavaScript code to be executed as string
	Code string `json:"code"`
	// Key-value environment variables to be passed to the transformation
	Env map[string]*UpsertTransformationRequestEnvValue `json:"env,omitempty"`
}
