// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	strconv "strconv"
)

// Bookmark target
type TriggerBookmarkRequestTarget uint8

const (
	TriggerBookmarkRequestTargetHttp TriggerBookmarkRequestTarget = iota + 1
	TriggerBookmarkRequestTargetCli
)

func (t TriggerBookmarkRequestTarget) String() string {
	switch t {
	default:
		return strconv.Itoa(int(t))
	case TriggerBookmarkRequestTargetHttp:
		return "http"
	case TriggerBookmarkRequestTargetCli:
		return "cli"
	}
}

func (t TriggerBookmarkRequestTarget) MarshalJSON() ([]byte, error) {
	return []byte(fmt.Sprintf("%q", t.String())), nil
}

func (t *TriggerBookmarkRequestTarget) UnmarshalJSON(data []byte) error {
	var raw string
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	switch raw {
	case "http":
		value := TriggerBookmarkRequestTargetHttp
		*t = value
	case "cli":
		value := TriggerBookmarkRequestTargetCli
		*t = value
	}
	return nil
}
