// This file was auto-generated by Fern from our API Definition.

package api

// TriggerBookmarkRequest is an in-lined request used by the TriggerBookmark endpoint.
type TriggerBookmarkRequest struct {
	// Bookmark target
	Target *TriggerBookmarkRequestTarget `json:"target,omitempty"`
}
