// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
)

type UpdateTransformationRequestEnvValue struct {
	typeName string
	String   string
	Double   float64
}

func NewUpdateTransformationRequestEnvValueFromString(value string) *UpdateTransformationRequestEnvValue {
	return &UpdateTransformationRequestEnvValue{typeName: "string", String: value}
}

func NewUpdateTransformationRequestEnvValueFromDouble(value float64) *UpdateTransformationRequestEnvValue {
	return &UpdateTransformationRequestEnvValue{typeName: "double", Double: value}
}

func (u *UpdateTransformationRequestEnvValue) UnmarshalJSON(data []byte) error {
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		u.typeName = "string"
		u.String = valueString
		return nil
	}
	var valueDouble float64
	if err := json.Unmarshal(data, &valueDouble); err == nil {
		u.typeName = "double"
		u.Double = valueDouble
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, u)
}

func (u UpdateTransformationRequestEnvValue) MarshalJSON() ([]byte, error) {
	switch u.typeName {
	default:
		return nil, fmt.Errorf("invalid type %s in %T", u.typeName, u)
	case "string":
		return json.Marshal(u.String)
	case "double":
		return json.Marshal(u.Double)
	}
}

type UpdateTransformationRequestEnvValueVisitor interface {
	VisitString(string) error
	VisitDouble(float64) error
}

func (u *UpdateTransformationRequestEnvValue) Accept(v UpdateTransformationRequestEnvValueVisitor) error {
	switch u.typeName {
	default:
		return fmt.Errorf("invalid type %s in %T", u.typeName, u)
	case "string":
		return v.VisitString(u.String)
	case "double":
		return v.VisitDouble(u.Double)
	}
}
