// This file was auto-generated by Fern from our API Definition.

package api

type UpdateBookmarkRequest struct {
	// ID of the event data to bookmark <span style="white-space: nowrap">`<= 255 characters`</span>
	EventDataId *string `json:"event_data_id,omitempty"`
	// ID of the associated connection <span style="white-space: nowrap">`<= 255 characters`</span>
	WebhookId *string `json:"webhook_id,omitempty"`
	// Descriptive name of the bookmark <span style="white-space: nowrap">`<= 255 characters`</span>
	Label *string `json:"label,omitempty"`
	// A unique, human-friendly name for the bookmark <span style="white-space: nowrap">`<= 155 characters`</span>
	Name *string `json:"name,omitempty"`
}
