// This file was auto-generated by Fern from our API Definition.

package api

// UpsertRulesetRequest is an in-lined request used by the UpsertRuleset endpoint.
type UpsertRulesetRequest struct {
	// Name for the ruleset <span style="white-space: nowrap">`<= 155 characters`</span>
	Name string `json:"name"`
	// Array of rules to apply
	Rules         *[]*Rule `json:"rules,omitempty"`
	IsTeamDefault *bool    `json:"is_team_default,omitempty"`
}
