// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	strconv "strconv"
)

// Period to rate limit attempts
type UpsertDestinationRequestRateLimitPeriod uint8

const (
	UpsertDestinationRequestRateLimitPeriodSecond UpsertDestinationRequestRateLimitPeriod = iota + 1
	UpsertDestinationRequestRateLimitPeriodMinute
	UpsertDestinationRequestRateLimitPeriodHour
)

func (u UpsertDestinationRequestRateLimitPeriod) String() string {
	switch u {
	default:
		return strconv.Itoa(int(u))
	case UpsertDestinationRequestRateLimitPeriodSecond:
		return "second"
	case UpsertDestinationRequestRateLimitPeriodMinute:
		return "minute"
	case UpsertDestinationRequestRateLimitPeriodHour:
		return "hour"
	}
}

func (u UpsertDestinationRequestRateLimitPeriod) MarshalJSON() ([]byte, error) {
	return []byte(fmt.Sprintf("%q", u.String())), nil
}

func (u *UpsertDestinationRequestRateLimitPeriod) UnmarshalJSON(data []byte) error {
	var raw string
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	switch raw {
	case "second":
		value := UpsertDestinationRequestRateLimitPeriodSecond
		*u = value
	case "minute":
		value := UpsertDestinationRequestRateLimitPeriodMinute
		*u = value
	case "hour":
		value := UpsertDestinationRequestRateLimitPeriodHour
		*u = value
	}
	return nil
}
